version: '3.1'
services:
  db:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'myfancypwd'

  hornherzogen:
    image: hornherzogen:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80
