version: '3.1'
services:
  db:
    image: mysql:8.0.12
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'myfancypwd'

  hornherzogen:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile 
