<!DOCTYPE HTML>
<html>
<head>
    <style>
        .error {color: #FF0000;}
    </style>
</head>
<body>

<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if (empty($_POST["count"]) || !is_numeric($_POST["count"])) {
        $count = 10; // fallback to default
    } else {
        $count = test_input($_POST["count"]);
    }
}

function test_input($data) {
    $data = trim($data);
    $data = stripslashes($data);
    $data = htmlspecialchars($data);
    return $data;
}
?>

<h2>PHP <?php echo phpversion(); ?> - Form Validation - let's see if parameters are missing</h2>

<h2>Form example</h2>
<form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
    Anzahl: <input type="text" name="count" value="<?php echo $count;?>">
    <br><br>
    <input type="submit" name="submit" value="Submit">

    <?php
    echo "<h2>Your Input:</h2>";
    echo '<pre>';
    echo '<p>RAW data after submit:</p>';
    var_dump(file_get_contents('php://input'));
    echo '<p>Converted to POST:</p>';
    var_dump($_POST);
    echo '</pre>';
    ?>

    <h3>Autogenerated field values to be ignored ;-)</h3>
    <?php

    for ($i = 1; $i <= 10; $i++) {
        echo '
        <br><br>
        Name '.$i.': <input type="text" name="name'.$i.'" value="Do not edit field '.$i.'">
    ';
    }

    ?>

</form>

</body>
</html>